trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build_Stage
    displayName:
    jobs:
      - job: BuildNuget
        displayName: Build Nuget packages
        variables:
          BuildConfiguration: release
        steps:
        - task: NuGetCommand@2
          inputs:
            command: 'restore'
            restoreSolution: '$(Build.ArtifactStagingDirectory)/DJH.BenefitPipe/*.csproj'
            feedsToUse: 'select'
            vstsFeed: '1b4829bf-22af-4b66-82e2-4c258baf759e/5d29b41f-f690-4420-bc53-983eda137f11'
        - task: NuGetCommand@2
          inputs:
            command: 'pack'
            packagesToPack: '$(Build.ArtifactStagingDirectory)/DJH.BenefitPipe/*.csproj'
            versioningScheme: 'off'
        - task: NuGetCommand@2
          inputs:
            command: 'push'
            packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
            nuGetFeedType: 'internal'
            publishVstsFeed: '1b4829bf-22af-4b66-82e2-4c258baf759e/5d29b41f-f690-4420-bc53-983eda137f11'
